baseURL = "http://nutch.apache.org/"
languageCode = "en-us"
theme = "SimpleIntro"
#title = "Apache Nutch"
publishDir = "public"

[params]
    mainbg = "./img/IMG_0295.png"
    pagebg = "../img/background.jpg"
    name = "Apache Nutch"
    mainTitle = "Apache Nutch"
    mainText = "Highly extensible, highly scalable, production-ready Web crawler"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "community"
        name = "Community"
        url = "/community"
    [[menu.main]]
        identifier = "development"
        name = "Development"
        url = "/development"
    [[menu.main]]
        identifier = "documentation"
        name = "Documentation"
        url = "/documentation"
    [[menu.main]]
        identifier = "downloads"
        name = "Downloads"
        url = "/downloads"
    [[menu.single]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 20
    [[menu.single]]
        identifier = "community"
        name = "Community"
        url = "/community"
    [[menu.single]]
        identifier = "development"
        name = "Development"
        url = "/development"
    [[menu.single]]
        identifier = "documentation"
        name = "Documentation"
        url = "/documentation"
    [[menu.single]]
        identifier = "downloads"
        name = "Downloads"
        url = "/downloads"